{
 "title": "REFIT Dashboard",
 "time": { "from": "2020-06-28T00:48:13.799Z", "to": "2020-06-28T00:50:19.887Z" },
 "templating": {
  "list": [
   { "name": "org", "label": "org" },
   { "name": "project", "label": "project" },
   { "name": "sensor", "label": "Sensor(s)" }
  ]
 },
 "panels": [
  {
   "title": "Operable",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "Prediction - output_label", "type": "timeseries" },
    { "target": "Actual - output_label", "type": "timeseries" }
   ]
  },
  {
   "title": "Wind",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "Wind", "type": "timeseries" }
   ]
  },
  {
   "title": "Pressure",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "Pressure", "type": "timeseries" }
   ]
  },
  {
   "title": "Temperature",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "Temperature", "type": "timeseries" }
   ]
  },
  {
   "title": "Sensor Activity",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short", "label": "Readings" }
   ],
   "targets": [
    { "target": "SensorID", "type": "timeseries" }
   ]
  }
 ]
}