# This is a basic workflow to help you get started with Actions

# name: Python CI

# # Controls when the action will run. Triggers the workflow on push or pull request
# # events but only for the master branch
# on:
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]

# # A workflow run is made up of one or more jobs that can run sequentially or in parallel
# jobs:
#   python-test:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - name: Set up Python 3.7
#         uses: actions/setup-python@v2
#         with:
#           # Semantic version range syntax or exact version of a Python version
#           python-version: '3.7'
#           # Optional - x64 or x86 architecture, defaults to x64
#           architecture: 'x64'
#       - name: Install dependencies
#         run: |
#           python -m pip install --upgrade pip
#           python setup.py install
#           pip install pytest
#           pip install -r requirements.txt
#         working-directory: training/
#       - name: Run Tests
#         run:  pytest
#         working-directory: training/
