package edu.cdl.iot.common.constants

object EnvConstants {
  val PULSAR_HOST = "PULSAR_HOST"
  val DATA_TOPIC = "PULSAR_DATA_TOPIC"
  val MODELS_TOPIC = "PULSAR_MODELS_TOPIC"
  val PREDICTIONS_TOPIC = "PULSAR_PREDICTIONS_TOPIC"
  val IMPORT_TOPIC = "PULSAR_IMPORT_TOPIC"
  val MODEL_PUBLISH_TOPIC = "PULSAR_MODEL_PUBLISH_TOPIC"
  val CASSANDRA_KEYSPACE = "CASSANDRA_KEYSPACE"
  val CASSANDRA_HOST = "CASSANDRA_HOST"
  val CASSANDRA_PORT = "CASSANDRA_PORT"
  val CASSANDRA_USER = "CASSANDRA_USER"
  val CASSANDRA_PASSWORD = "CASSANDRA_PASSWORD"
  val ENCRYPTION_KEY = "ENCRYPTION_KEY"
  val PROJECT = "PROJECT"
  val DEMO = "REFIT_DEMO"
  val MINIO_HOST = "MINIO_HOST"
  val MINIO_ACCESS_KEY = "MINIO_ACCESS_KEY"
  val MINIO_SECRET_KEY = "MINIO_SECRET_KEY"
  val MINIO_BUCKET_IMPORT = "MINIO_BUCKET_IMPORT"
  val MINIO_BUCKET_MODELS = "MINIO_BUCKET_MODELS"
  val MINIO_BUCKET_SCHEMA = "MINIO_BUCKET_SCHEMA"
}

