package edu.cdl.iot.common.constants

object EnvConstants {
  val PULSAR_HOST = "PULSAR_HOST"
  val CASSANDRA_KEYSPACE = "CASSANDRA_KEYSPACE"
  val CASSANDRA_HOST = "CASSANDRA_HOST"
  val CASSANDRA_PORT = "CASSANDRA_PORT"
  val CASSANDRA_USER = "CASSANDRA_USER"
  val CASSANDRA_PASSWORD = "CASSANDRA_PASSWORD"
  val ENCRYPTION_KEY = "ENCRYPTION_KEY"
  val PROJECT = "PROJECT"
}

