apiVersion: v1
kind: Pod
metadata:
  labels:
    app: jenkins-agent
spec:
  containers:
  - name: inference
    image: cdliotprototype/build-agent:latest
    command:
    - cat
    tty: true
  - name: sbt
    image: mozilla/sbt
    command:
      - cat
    tty: true
  nodeSelector:
    coredns: enabled