apiVersion: v1
kind: Pod
metadata:
  labels:
    app: jenkins-agent
spec:
  containers:
  - name: nodejs
    image: node:14-alpine
    command:
    - cat
    tty: true
  nodeSelector:
    coredns: enabled