apiVersion: v1
kind: Pod
metadata:
  labels:
    app: jenkins-agent
spec:
  containers:
  - name: sbt
    image: mozilla/sbt
    command:
    - cat
    tty: true
  - name: flink-submit
    image: library/flink:1.10.1-scala_2.11
    command:
      - cat
    tty: true
  nodeSelector:
    coredns: enabled