#!/bin/sh


docker-compose build
docker-compose up --force-recreate -d

if [ "$1" == "demo" ]; then
    pulsar-client consume persistent://public/standalone/default/event-log -n 0 -s tst-consumer
fi 
