apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-flink-jobmanager-rest
  labels:
    app: {{ .Release.Name }}-flink
    meta.helm.sh/release-name: "{{ .Release.Name }}"
    meta.helm.sh/release-namespace: "{{ .Release.Namespace }}"
  annotations:
    meta.helm.sh/release-name: "{{ .Release.Name }}"
    meta.helm.sh/release-namespace: "{{ .Release.Namespace }}"
spec:
  type: NodePort
  ports:
  - name: rest
    port: 8081
    targetPort: 8081
  selector:
    app: {{ .Release.Name }}-flink
    component: {{ .Release.Name }}-flink-jobmanager