apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-flink-jobmanager-rest
spec:
  type: NodePort
  ports:
  - name: rest
    port: 8081
    targetPort: 8081
  selector:
    app: {{ .Release.Name }}-flink
    component: {{ .Release.Name }}-flink-jobmanager