#! /bin/sh

[[ -d ./refit ]] && rm -rf ./refit
cp -r /libs/refit/ ./refit/
pip3 install -q -r refit/requirements.txt

echo "Refit Installed, You can now run the following to import REFIT"
echo "from refit.api.refit import Refit"