version: '3.8'
services:
  zookeeper:
    image: 'bitnami/zookeeper:3.5'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  refit-kafka:
    image: 'bitnami/kafka:2.1.0'
    ports:
      - '9092:9092'
      - '19092:19092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=EXTERNAL://0.0.0.0:19092,PLAINTEXT://0.0.0.0:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://refit-kafka:9092,EXTERNAL://127.0.0.1:19092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
  #
  postgres:
    build: ./resources/pql
    ports:
      - "5432:5432"
    environment:
      - POSTGRESQL_PASSWORD=refit
      - POSTGRESQL_USERNAME=refit
      - POSTGRESQL_DATABASE=refit
    volumes:
      - postgres:/bitnami
  cassandra:
    build: ./resources/cql
    ports:
      - "7000:7000"
      - "9042:9042"
      - "9160:9160"
    volumes:
      - cassandra:/bitnami
  grafana:
    image: grafana/grafana:7.1.1
    volumes:
      - ./resources/grafana/provisioning/:/etc/grafana/provisioning
      - ./resources/grafana/config.ini:/etc/grafana/config.ini
      - ./resources/grafana/dashboards/:/var/lib/grafana/dashboards
    ports:
      - 8000:8000
    user: "104"
    environment:
      GF_INSTALL_PLUGINS: grafana-clock-panel,grafana-simple-json-datasource,simpod-json-datasource

  flink-jobmanager:
    #    image: cdliotprototype/cdl-refit-flink:BETA-TEST-0.3
    build: resources/flink
    ports:
      - "8081:8081"
    command: jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: flink-jobmanager
        taskmanager.numberOfTaskSlots: 2
        taskmanager.memory.jvm-metaspace.size: 500 mb
        classloader.resolve-order: parent-first
        blob.server.port: 6124
        containerized.taskmanager.env.MINIO_HOST: /usr/lib/native
        containerized.taskmanager.env.MINIO_ACCESS_KEY: /usr/lib/native
        containerized.taskmanager.env.MINIO_SECRET_KEY: /usr/lib/native
        containerized.taskmanager.env.MINIO_BUCKET_IMPORT: /usr/lib/native
        containerized.taskmanager.env.MINIO_BUCKET_MODELS: /usr/lib/native
        containerized.taskmanager.env.MINIO_BUCKET_SCHEMA: /usr/lib/native
        containerized.taskmanager.env.KAFKA_HOST: /usr/lib/native
        containerized.taskmanager.env.KAFKA_DATA_TOPIC: /usr/lib/native
        containerized.taskmanager.env.MODEL_PUBLISHED_TOPIC: /usr/lib/native
        containerized.taskmanager.env.MODEL_DEPLOYED_TOPIC: /usr/lib/native
        containerized.taskmanager.env.PREDICTIONS_TOPIC: /usr/lib/native
        containerized.taskmanager.env.IMPORT_TOPIC: /usr/lib/native
        containerized.taskmanager.env.RAW_SENSOR_DATA_TOPIC: /usr/lib/native
        containerized.taskmanager.env.SENSOR_DATA_TOPIC: /usr/lib/native
      - KAFKA_HOST=refit-kafka:9092
      - KAFKA_DATA_TOPIC=refit.inference.data
      - KAFKA_MODEL_PUBLISHED_TOPIC=refit.training.models
      - KAFKA_PREDICTIONS_TOPIC=refit.inference.predictions
      - KAFKA_IMPORT_TOPIC=refit.training.import
      - KAFKA_RAW_SENSOR_DATA_TOPIC=refit.inference.raw.data
      - KAFKA_SENSOR_DATA_TOPIC=refit.inference.sensor.data
      - MINIO_HOST=http://minio:9000
      - MINIO_ACCESS_KEY=refit
      - MINIO_SECRET_KEY=refit-key
      - MINIO_BUCKET_IMPORT=refit-import
      - MINIO_BUCKET_MODELS=refit-models
      - MINIO_BUCKET_SCHEMA=refit-schema
      - ENCRYPTION_KEY=keyboard_cat
      - REFIT_DEMO="true"
      - PROJECT=ingestion

  flink-taskmanager:
    #    image: cdliotprototype/cdl-refit-flink:BETA-TEST-0.3
    build: resources/flink
    depends_on:
      - flink-jobmanager
    command: taskmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: flink-jobmanager
        taskmanager.numberOfTaskSlots: 2
        taskmanager.memory.jvm-metaspace.size: 500 mb
        classloader.resolve-order: parent-first
        blob.server.port: 6124
        s3.path-style: true
        s3.endpoint: http://minio:9000
        s3.access-key: refit
        s3.secret-key: refit-key
        hive.s3.aws-access-key: refit
        hive.s3.aws-secret-key: refit-key
        hive.s3.endpoint: http://minio:9000
        s3.path.style.access: true
        containerized.taskmanager.env.PROJECT: /usr/lib/native
        containerized.taskmanager.env.MINIO_HOST: /usr/lib/native
        containerized.taskmanager.env.MINIO_HOST: /usr/lib/native
        containerized.taskmanager.env.MINIO_ACCESS_KEY: /usr/lib/native
        containerized.taskmanager.env.MINIO_SECRET_KEY: /usr/lib/native
        containerized.taskmanager.env.MINIO_BUCKET_IMPORT: /usr/lib/native
        containerized.taskmanager.env.MINIO_BUCKET_MODELS: /usr/lib/native
        containerized.taskmanager.env.MINIO_BUCKET_SCHEMA: /usr/lib/native
        containerized.taskmanager.env.KAFKA_HOST: /usr/lib/native
        containerized.taskmanager.env.KAFKA_DATA_TOPIC: /usr/lib/native
        containerized.taskmanager.env.MODEL_PUBLISHED_TOPIC: /usr/lib/native
        containerized.taskmanager.env.MODEL_DEPLOYED_TOPIC: /usr/lib/native
        containerized.taskmanager.env.PREDICTIONS_TOPIC: /usr/lib/native
        containerized.taskmanager.env.IMPORT_TOPIC: /usr/lib/native
        containerized.taskmanager.env.RAW_SENSOR_DATA_TOPIC: /usr/lib/native
        containerized.taskmanager.env.SENSOR_DATA_TOPIC: /usr/lib/native
      - KAFKA_HOST=refit-kafka:9092
      - KAFKA_DATA_TOPIC=refit.inference.data
      - KAFKA_MODEL_PUBLISHED_TOPIC=refit.training.models
      - KAFKA_PREDICTIONS_TOPIC=refit.inference.predictions
      - KAFKA_IMPORT_TOPIC=refit.training.import
      - KAFKA_RAW_SENSOR_DATA_TOPIC=refit.inference.raw.data
      - KAFKA_SENSOR_DATA_TOPIC=refit.inference.sensor.data
      - MINIO_HOST=http://minio:9000
      - MINIO_ACCESS_KEY=refit
      - MINIO_SECRET_KEY=refit-key
      - MINIO_BUCKET_IMPORT=refit-import
      - MINIO_BUCKET_MODELS=refit-models
      - MINIO_BUCKET_SCHEMA=refit-schema
      - ENCRYPTION_KEY=keyboard_cat
      - REFIT_DEMO="true"
      - PROJECT=ingestion

  flink-taskmanager-2:
    #    image: cdliotprototype/cdl-refit-flink:BETA-TEST-0.3
    build: resources/flink
    depends_on:
      - flink-jobmanager
    command: taskmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: flink-jobmanager
        taskmanager.numberOfTaskSlots: 2
        taskmanager.memory.jvm-metaspace.size: 500 mb
        classloader.resolve-order: parent-first
        blob.server.port: 6124
        s3.path-style: true
        s3.endpoint: http://minio:9000
        s3.access-key: refit
        s3.secret-key: refit-key
        hive.s3.aws-access-key: refit
        hive.s3.aws-secret-key: refit-key
        hive.s3.endpoint: http://minio:9000
        s3.path.style.access: true
        containerized.taskmanager.env.PROJECT: /usr/lib/native
        containerized.taskmanager.env.MINIO_HOST: /usr/lib/native
        containerized.taskmanager.env.MINIO_HOST: /usr/lib/native
        containerized.taskmanager.env.MINIO_ACCESS_KEY: /usr/lib/native
        containerized.taskmanager.env.MINIO_SECRET_KEY: /usr/lib/native
        containerized.taskmanager.env.MINIO_BUCKET_IMPORT: /usr/lib/native
        containerized.taskmanager.env.MINIO_BUCKET_MODELS: /usr/lib/native
        containerized.taskmanager.env.MINIO_BUCKET_SCHEMA: /usr/lib/native
        containerized.taskmanager.env.KAFKA_HOST: /usr/lib/native
        containerized.taskmanager.env.KAFKA_DATA_TOPIC: /usr/lib/native
        containerized.taskmanager.env.MODEL_PUBLISHED_TOPIC: /usr/lib/native
        containerized.taskmanager.env.MODEL_DEPLOYED_TOPIC: /usr/lib/native
        containerized.taskmanager.env.PREDICTIONS_TOPIC: /usr/lib/native
        containerized.taskmanager.env.IMPORT_TOPIC: /usr/lib/native
        containerized.taskmanager.env.RAW_SENSOR_DATA_TOPIC: /usr/lib/native
        containerized.taskmanager.env.SENSOR_DATA_TOPIC: /usr/lib/native
      - KAFKA_HOST=refit-kafka:9092
      - KAFKA_DATA_TOPIC=refit.inference.data
      - KAFKA_MODEL_PUBLISHED_TOPIC=refit.training.models
      - KAFKA_PREDICTIONS_TOPIC=refit.inference.predictions
      - KAFKA_IMPORT_TOPIC=refit.training.import
      - KAFKA_RAW_SENSOR_DATA_TOPIC=refit.inference.raw.data
      - KAFKA_SENSOR_DATA_TOPIC=refit.inference.sensor.data
      - MINIO_HOST=http://minio:9000
      - MINIO_ACCESS_KEY=refit
      - MINIO_SECRET_KEY=refit-key
      - MINIO_BUCKET_IMPORT=refit-import
      - MINIO_BUCKET_MODELS=refit-models
      - MINIO_BUCKET_SCHEMA=refit-schema
      - ENCRYPTION_KEY=keyboard_cat
      - REFIT_DEMO="true"
      - PROJECT=ingestion


  minio:
    image: minio/minio:RELEASE.2020-09-17T04-49-20Z
    volumes:
      - minio-1:/data
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: refit
      MINIO_SECRET_KEY: refit-key
    command: server /data
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3

  inference:
    build: ./inference/inference-application
    environment:
      WAIT_FLINK_HOST: flink-jobmanager
      FLINK_HOST: flink-jobmanager
      KAFKA_HOST: "refit-kafka:9092"
    depends_on:
      - flink-jobmanager
      - refit-kafka
      - cassandra

  ingestion:
    build: ./ingestion/ingestion-application
    environment:
      - WAIT_CASSANDRA_HOST=cassandra
      - KAFKA_HOST=refit-kafka:9092
      - KAFKA_DATA_TOPIC=refit.inference.data
      - KAFKA_MODEL_PUBLISHED_TOPIC=refit.training.models
      - KAFKA_PREDICTIONS_TOPIC=refit.inference.predictions
      - KAFKA_IMPORT_TOPIC=refit.training.import
      - KAFKA_RAW_SENSOR_DATA_TOPIC=refit.inference.raw.data
      - KAFKA_SENSOR_DATA_TOPIC=refit.inference.sensor.data
      - CASSANDRA_HOST=cassandra
      - CASSANDRA_PORT=9042
      - CASSANDRA_USER=cassandra
      - CASSANDRA_PASSWORD=cassandra
      - CASSANDRA_KEYSPACE=cdl_refit
      - MINIO_HOST=http://minio:9000
      - MINIO_ACCESS_KEY=refit
      - MINIO_SECRET_KEY=refit-key
      - MINIO_BUCKET_IMPORT=refit-import
      - MINIO_BUCKET_MODELS=refit-models
      - MINIO_BUCKET_SCHEMA=refit-schema
      - ENCRYPTION_KEY=keyboard_cat
      - REFIT_DEMO=true
      - PROJECT=ingestion
    depends_on:
      - flink-jobmanager
      - refit-kafka
      - cassandra
    ports:
      - "3030:3030"

  integrations:
    build: ./integrations/integrations-application
    environment:
      - WAIT_CASSANDRA_HOST=cassandra
      - KAFKA_HOST=refit-kafka:9092
      - KAFKA_DATA_TOPIC=refit.inference.data
      - KAFKA_MODEL_PUBLISHED_TOPIC=refit.training.models
      - KAFKA_PREDICTIONS_TOPIC=refit.inference.predictions
      - KAFKA_IMPORT_TOPIC=refit.training.import
      - KAFKA_RAW_SENSOR_DATA_TOPIC=refit.inference.raw.data
      - KAFKA_SENSOR_DATA_TOPIC=refit.inference.sensor.data
      - CASSANDRA_HOST=cassandra
      - CASSANDRA_PORT=9042
      - CASSANDRA_USER=cassandra
      - CASSANDRA_PASSWORD=cassandra
      - CASSANDRA_KEYSPACE=cdl_refit
      - MINIO_HOST=http://minio:9000
      - MINIO_ACCESS_KEY=refit
      - MINIO_SECRET_KEY=refit-key
      - MINIO_BUCKET_IMPORT=refit-import
      - MINIO_BUCKET_MODELS=refit-models
      - MINIO_BUCKET_SCHEMA=refit-schema
      - ENCRYPTION_KEY=keyboard_cat
      - REFIT_DEMO=true
      - PROJECT=integrations
    depends_on:
      - flink-jobmanager
      - refit-kafka
      - cassandra
    ports:
      - "3000:3000"


  notebook:
    build: ./training/
    # image: jupyter/base-notebook:latest
    volumes:
      - ./training/:/home/docker_worker
    ports:
      - 8888:8888
    command: "start-notebook.sh"
    user: root
    environment:
      JUPYTER_ENABLE_LAB: 'yes'
      NB_USER: docker_worker
      NB_UID: 1008
      NB_GID: 1011
      CHOWN_HOME: 'yes'
      CHOWN_HOME_OPTS: -R
      MINIO_HOST: minio:9000
      MINIO_ACCESS_KEY: refit
      MINIO_SECRET_KEY: refit-key
      MINIO_BUCKET_IMPORT: refit-import
      MINIO_BUCKET_MODELS: refit-models
      MINIO_BUCKET_SCHEMA: refit-schema
      ENCRYPTION_KEY: keyboard_cat
      REFIT_DEMO: "false"
      PROJECT: ingestion
      INTEGRATIONS_HOST: integrations
      FLINK_HOST: flink-jobmanager

networks:
  default:
    driver: bridge

volumes:
  minio-1:
  cassandra:
  postgres: