apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-db
  labels:
    meta.helm.sh/release-name: "{{ .Release.Name }}"
    meta.helm.sh/release-namespace: "{{ .Release.Namespace }}"
  annotations:
    meta.helm.sh/release-name: "{{ .Release.Name }}"
    meta.helm.sh/release-namespace: "{{ .Release.Namespace }}"
    "helm.sh/hook": post-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        component: db
    spec:
      restartPolicy: OnFailure
      containers:
        - name: {{ .Release.Name }}-db
          image: cdliotprototype/cdl-refit-db:{{ .Values.refit.version }}
          env:
            - name: REFIT_PROJECT
              value: db
            - name: PULSAR_HOST
              value: {{ .Release.Name }}-pulsar-standalone
            - name: CASSANDRA_HOST
              value: {{ .Release.Name }}-cassandra
            - name: CASSANDRA_PORT
              value: "9042"
            - name: CASSANDRA_KEYSPACE
              value: cdl_refit
            - name: CASSANDRA_USERNAME
              value: cassandra
            - name: CASSANDRA_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: cassandra-password
                  name: refit-cassandra-credentials
            - name: ENCRYPTION_KEY
              valueFrom:
                secretKeyRef:
                  key: password
                  name: {{ .Release.Name }}-encryption-key
  {{- with .Values.refit.nodeSelector }}
      nodeSelector:
      {{- toYaml . | nindent 8 }}
  {{- end }}