{
 "title": "REFIT Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "org", "label": "org" },
   { "name": "project", "label": "project" },
   { "name": "sensor", "label": "Sensor(s)" }
  ]
 },
 "panels": [
  {
   "title": "Sensor Activity",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Readings" }
   ],
   "targets": [
    { "target": "SensorID", "type": "timeseries" }
   ]
  },
  {
   "title": "Wind",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "Wind", "type": "timeseries" }
   ]
  },
  {
   "title": "Pressure",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "Pressure", "type": "timeseries" }
   ]
  },
  {
   "title": "Temperature",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "Temperature", "type": "timeseries" }
   ]
  },
  {
   "title": "Operable",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "Operable", "type": "timeseries" }
   ]
  },
  {
   "title": "Operable - P(1)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "Probability(1)", "type": "timeseries" }
   ]
  },
  {
   "title": "Operable - P(0)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "Probability(0)", "type": "timeseries" }
   ]
  }
 ]
}