cluster:
  replicaCount: 4
  seedCount: 4
persistence:
  enabled: false
  # storageClass: glusterfs
dbUser:
  user: cassandra
  password: cassandra

nodeSelector: 
  coredns: enabled
resources:
  limits:
    memory: "10000Mi"
  requests:
    memory: "3000Mi"