apiVersion: v1
kind: Namespace
metadata:
  name: iot-prototype
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: glusterfs
provisioner: kubernetes.io/glusterfs
parameters:
  resturl: "http://gluster-cluster:8080"
  restuser: ""
  secretNamespace: ""
  secretName: ""
  gidMin: "40000"
  gidMax: "50000"
allowVolumeExpansion: true
---
apiVersion: v1
kind: Service
metadata:
  name: gluster-cluster 
spec:
  ports:
  - port: 1
---
apiVersion: v1
kind: Endpoints
metadata:
  name: gluster-cluster 
subsets:
  - addresses:
      - ip: 10.14.38.61
    ports:
      - port: 1 
  - addresses:
      - ip: 10.14.38.62
    ports:
      - port: 1 
  - addresses:
      - ip: 10.14.38.64
    ports:
      - port: 1 