apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-inference
  labels:
    meta.helm.sh/release-name: "{{ .Release.Name }}"
    meta.helm.sh/release-namespace: "{{ .Release.Namespace }}"
  annotations:
    meta.helm.sh/release-name: "{{ .Release.Name }}"
    meta.helm.sh/release-namespace: "{{ .Release.Namespace }}"
    "helm.sh/hook": post-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        component: inference
    spec:
      restartPolicy: OnFailure
      containers:
        - name: {{ .Release.Name }}-inference
          image: cdliotprototype/cdl-refit-inference:{{ .Values.refit.version }}
          env:
            - name: REFIT_PROJECT
              value: inference
            - name: PULSAR_HOST
              value: {{ .Release.Name }}-pulsar-standalone
            - name: FLINK_HOST
              value: {{ .Release.Name }}-flink-jobmanager
  {{- with .Values.refit.nodeSelector }}
      nodeSelector:
      {{- toYaml . | nindent 8 }}
  {{- end }}